PetWebs/Models/Mascota.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWebs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.Atencion = new HashSet<Atencion>();
            this.Desparacitacion = new HashSet<Desparacitacion>();
            this.Examen = new HashSet<Examen>();
            this.Vacuna = new HashSet<Vacuna>();
        }
    
        public int Microchip { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public decimal Peso { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<bool> Esterilizado { get; set; }
        public Nullable<bool> Defuncion { get; set; }
        public Nullable<System.DateTime> FechaDef { get; set; }
        public string CausaDef { get; set; }
        public string ObserDef { get; set; }
        public Nullable<int> Rut { get; set; }
        public Nullable<int> Especie { get; set; }
        public Nullable<int> Raza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atencion> Atencion { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desparacitacion> Desparacitacion { get; set; }
        public virtual Especie Especie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen> Examen { get; set; }
        public virtual Raza Raza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacuna> Vacuna { get; set; }
    }
}

PetWebs/Controllers/MascotasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PetWebs.Models;

namespace PetWebs.Controllers
{
    public class MascotasController : Controller
    {
        private PETWEBSEntities db = new PETWEBSEntities();

        // GET: Mascotas
        public ActionResult MascList()
        {
            var mascota = db.Mascota.Include(m => m.Cliente).Include(m => m.Especie1).Include(m => m.Raza1);
            return View(mascota.ToList());
        }

        // GET: Mascotas/Details/5
        public ActionResult Details(string Rut)
        {
            if (Rut == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mascota mascota = db.Mascota.Find(Rut);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            return View(mascota);
        }

        // GET: Mascotas/Create
        public ActionResult Create()
        {
            ViewBag.Rut = new SelectList(db.Cliente, "Rut", "Nombre");
            ViewBag.Especie = new SelectList(db.Especie, "Id", "Tipo");
            ViewBag.Raza = new SelectList(db.Raza, "Id", "Nombre");
            return View();
        }

        // POST: Mascotas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Microchip,Nombre,Sexo,Peso,Color,FechaNacimiento,Esterilizado,Defuncion,FechaDef,CausaDef,ObserDef,Rut,Especie,Raza")] Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                db.Mascota.Add(mascota);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Rut = new SelectList(db.Cliente, "Rut", "Nombre", mascota.Rut);
            ViewBag.Especie = new SelectList(db.Especie, "Id", "Tipo", mascota.Especie);
            ViewBag.Raza = new SelectList(db.Raza, "Id", "Nombre", mascota.Raza);
            return View(mascota);
        }

        // GET: Mascotas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mascota mascota = db.Mascota.Find(id);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            ViewBag.Rut = new SelectList(db.Cliente, "Rut", "Nombre", mascota.Rut);
            ViewBag.Especie = new SelectList(db.Especie, "Id", "Tipo", mascota.Especie);
            ViewBag.Raza = new SelectList(db.Raza, "Id", "Nombre", mascota.Raza);
            return View(mascota);
        }

        // POST: Mascotas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Microchip,Nombre,Sexo,Peso,Color,FechaNacimiento,Esterilizado,Defuncion,FechaDef,CausaDef,ObserDef,Rut,Especie,Raza")] Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mascota).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Rut = new SelectList(db.Cliente, "Rut", "Nombre", mascota.Rut);
            ViewBag.Especie = new SelectList(db.Especie, "Id", "Tipo", mascota.Especie);
            ViewBag.Raza = new SelectList(db.Raza, "Id", "Nombre", mascota.Raza);
            return View(mascota);
        }

        // GET: Mascotas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mascota mascota = db.Mascota.Find(id);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            return View(mascota);
        }

        // POST: Mascotas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Mascota mascota = db.Mascota.Find(id);
            db.Mascota.Remove(mascota);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetWebs/Views/Mascotas/Create.cshtml
@model PetWebs.Models.Mascota

@{
    ViewBag.Title = "Create";

}
@Styles.Render("~/Content/css")
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Mascota</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Microchip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Microchip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Microchip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Esterilizado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Esterilizado)
                    @Html.ValidationMessageFor(model => model.Esterilizado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Defuncion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Defuncion)
                    @Html.ValidationMessageFor(model => model.Defuncion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaDef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDef, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CausaDef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CausaDef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CausaDef, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ObserDef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ObserDef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ObserDef, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rut, "Rut", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Rut", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Rut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Especie, "Especie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Especie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Especie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raza, "Raza", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Raza", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Raza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PetWebs/Views/Mascotas/Delete.cshtml
@model PetWebs.Models.Mascota

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mascota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Esterilizado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Esterilizado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Defuncion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Defuncion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDef)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CausaDef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CausaDef)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObserDef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObserDef)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especie1.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especie1.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raza1.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Raza1.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PetWebs/Views/Mascotas/Index.cshtml
@model IEnumerable<PetWebs.Models.Mascota>

@Html.Partial("_LoginPartial")
@if (Request.IsAuthenticated)
{

    <div id="Menu">




        <div class="row ">
            <div class="col-2 " style="background-color:teal;">

                <br />
                <img class="rounded mx-auto d-block" src="~/Content/Img/Icon Menu.png " style="width:100px; height:100px; " />

                <br />
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home", null, new { style = " text-decoration:none; color: white;;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Mascotas*", "Index", "VW_NuevaFicha", null, new { style = " text-decoration:none; color: white;;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Nuevo Cliente", "NuevoCliente", "Clientes", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Nueva Mascota*", "Create", "Mascotas", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Defunción*", "Index", "VW_Defunciones", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Leyes*", "Leyees", "Home", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>

                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        <a href="javascript:document.getElementById('logoutForm').submit()" style="color:white;">Cerrar sesión</a>
                    </li>
                </ul>



            </div>

            <div class="col-lg-10" style="background-color: rgba(255, 255, 255, 0.89) ; max-height: 100%; padding:20px;">

                <br />

                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Sexo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Peso)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Color)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaNacimiento)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Esterilizado)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Defuncion)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaDef)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CausaDef)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ObserDef)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Cliente.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Especie1.Tipo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Raza1.Nombre)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sexo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Peso)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Color)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaNacimiento)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Esterilizado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Defuncion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaDef)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CausaDef)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ObserDef)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cliente.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Especie1.Tipo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Raza1.Nombre)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Microchip }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Microchip }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Microchip })
                            </td>
                        </tr>
                    }

                </table>


            </div>

            <br />
            <br />

        </div>

    </div>




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

}

PetWebs/Views/Mascotas/MascList.cshtml
@model IEnumerable<PetWebs.Models.Mascota>

@Html.Partial("_LoginPartial")
@if (Request.IsAuthenticated)
{

    <div id="Menu">




        <div class="row ">
            <div class="col-2 " style="background-color:teal;">

                <br />
                <img class="rounded mx-auto d-block" src="~/Content/Img/Icon Menu.png " style="width:100px; height:100px; " />

                <br />
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home", null, new { style = " text-decoration:none; color: white;;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Mascotas*", "Index", "VW_NuevaFicha", null, new { style = " text-decoration:none; color: white;;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Nuevo Cliente", "NuevoCliente", "Clientes", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Nueva Mascota*", "Create", "Mascotas", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Defunción*", "Index", "VW_Defunciones", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>
                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        @Html.ActionLink("Leyes*", "Leyees", "Home", null, new { style = " text-decoration:none; color: white;" })
                    </li>
                </ul>

                <ul style="list-style:none; " class="dropdown-item">
                    <li>
                        <a href="javascript:document.getElementById('logoutForm').submit()" style="color:white;">Cerrar sesión</a>
                    </li>
                </ul>



            </div>

            <div class="col-lg-10" style="background-color: rgba(255, 255, 255, 0.89) ; max-height: 100%; padding:20px;">

                <br />

                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Sexo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Peso)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Color)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaNacimiento)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Esterilizado)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Defuncion)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaDef)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CausaDef)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ObserDef)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Cliente.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Especie1.Tipo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Raza1.Nombre)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sexo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Peso)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Color)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaNacimiento)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Esterilizado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Defuncion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaDef)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CausaDef)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ObserDef)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cliente.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Especie1.Tipo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Raza1.Nombre)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Microchip }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Microchip }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Microchip })
                            </td>
                        </tr>
                    }

                </table>


            </div>

            <br />
            <br />

        </div>

    </div>




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

}